version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: gra

  node:
    build:
      context: .
      dockerfile: Node.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: nodemon /app/server.js
    depends_on:
      - mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  db_data: